import type { Recipe } from "./types"

export const RECIPES: Recipe[] = [
  {
    id: "r-spinach-feta-eggs",
    title: "Spinach & Feta Scrambled Eggs",
    subtitle: "A soft, herby skillet scramble that rescues wilting greens.",
    prepMinutes: 5,
    cookMinutes: 8,
    servings: 2,
    difficulty: "Easy",
    mealType: "Breakfast",
    tags: ["Vegetarian", "High Protein", "Quick & Easy", "Zero Waste Hero"],
    ingredients: [
      { name: "Eggs", quantity: "4 large", category: "Dairy", isPantryStaple: false },
      { name: "Baby Spinach", quantity: "2 handfuls", category: "Produce", isPantryStaple: false },
      { name: "Cheddar Cheese", quantity: "40g crumbled", category: "Dairy", isPantryStaple: false },
      { name: "Garlic", quantity: "1 clove", category: "Produce", isPantryStaple: true },
      { name: "Olive Oil", quantity: "1 tbsp", category: "Condiments", isPantryStaple: true },
      { name: "Salt & Pepper", quantity: "to taste", category: "Condiments", isPantryStaple: true },
    ],
    instructions: [
      "Whisk the eggs with a pinch of salt and pepper until fully combined.",
      "Warm the olive oil in a non-stick skillet over medium-low heat and soften the minced garlic for 30 seconds.",
      "Add the spinach and toss until just wilted, about 1 minute.",
      "Pour in the eggs and gently fold with a spatula, pulling from the edges to the center.",
      "When barely set, fold through the cheese and pull off the heat — carry-over will finish the cook.",
    ],
    tips: "Take the pan off the heat while the eggs still look slightly wet. They keep cooking on the way to the plate.",
  },
  {
    id: "r-garlic-chicken-skillet",
    title: "Creamy Garlic Chicken Skillet",
    subtitle: "Golden chicken in a silky, garlicky pan sauce.",
    prepMinutes: 10,
    cookMinutes: 20,
    servings: 2,
    difficulty: "Medium",
    mealType: "Dinner",
    tags: ["High Protein", "Zero Waste Hero"],
    ingredients: [
      { name: "Chicken Breast", quantity: "2 fillets", category: "Meat & Poultry", isPantryStaple: false },
      { name: "Garlic", quantity: "4 cloves", category: "Produce", isPantryStaple: true },
      { name: "Whole Milk", quantity: "150ml", category: "Dairy", isPantryStaple: false },
      { name: "Baby Spinach", quantity: "1 handful", category: "Produce", isPantryStaple: false },
      { name: "Olive Oil", quantity: "2 tbsp", category: "Condiments", isPantryStaple: true },
      { name: "Salt & Pepper", quantity: "to taste", category: "Condiments", isPantryStaple: true },
    ],
    instructions: [
      "Season the chicken generously on both sides.",
      "Sear in olive oil over medium-high heat until golden, about 5 minutes per side, then set aside.",
      "Lower the heat and soften the sliced garlic in the same pan until fragrant.",
      "Pour in the milk, scraping up the browned bits, and simmer until slightly thickened.",
      "Stir in the spinach, return the chicken, and spoon the sauce over until cooked through.",
    ],
    tips: "A splash of pasta water or a knob of butter loosens and enriches the sauce if it tightens too much.",
  },
  {
    id: "r-banana-bread-oats",
    title: "Banana Bread Baked Oats",
    subtitle: "Warm, cakey oats that taste like a slice of banana bread.",
    prepMinutes: 8,
    cookMinutes: 25,
    servings: 2,
    difficulty: "Easy",
    mealType: "Breakfast",
    tags: ["Vegetarian", "Budget Friendly", "Zero Waste Hero"],
    ingredients: [
      { name: "Bananas", quantity: "2 ripe", category: "Produce", isPantryStaple: false },
      { name: "Eggs", quantity: "1 large", category: "Dairy", isPantryStaple: false },
      { name: "Whole Milk", quantity: "120ml", category: "Dairy", isPantryStaple: false },
      { name: "Rolled Oats", quantity: "1 cup", category: "Pantry & Grains", isPantryStaple: true },
      { name: "Cinnamon", quantity: "1 tsp", category: "Condiments", isPantryStaple: true },
    ],
    instructions: [
      "Heat the oven to 190°C (375°F) and grease two small ramekins.",
      "Mash the bananas until mostly smooth, keeping a few lumps for texture.",
      "Whisk in the egg, milk, oats, and cinnamon until combined.",
      "Divide between the ramekins and bake for 22–25 minutes until set and golden.",
      "Cool briefly — the centers firm up as they rest.",
    ],
    tips: "The riper and spottier the bananas, the sweeter the bake. This is the perfect home for over-ripe fruit.",
  },
  {
    id: "r-tomato-basil-pasta",
    title: "Classic Tomato Basil Pasta",
    subtitle: "A 20-minute weeknight red sauce from the pantry.",
    prepMinutes: 5,
    cookMinutes: 20,
    servings: 3,
    difficulty: "Easy",
    mealType: "Dinner",
    tags: ["Vegetarian", "Budget Friendly", "Quick & Easy"],
    ingredients: [
      { name: "Pasta", quantity: "300g", category: "Pantry & Grains", isPantryStaple: true },
      { name: "Canned Tomatoes", quantity: "1 can", category: "Pantry & Grains", isPantryStaple: true },
      { name: "Garlic", quantity: "3 cloves", category: "Produce", isPantryStaple: true },
      { name: "Olive Oil", quantity: "3 tbsp", category: "Condiments", isPantryStaple: true },
      { name: "Cheddar Cheese", quantity: "to finish", category: "Dairy", isPantryStaple: false },
    ],
    instructions: [
      "Bring a large pot of salted water to the boil and cook the pasta to al dente.",
      "Meanwhile, gently sizzle the sliced garlic in olive oil until just golden.",
      "Add the canned tomatoes, crush them down, and simmer for 10–12 minutes.",
      "Toss the drained pasta through the sauce with a splash of pasta water.",
      "Finish with grated cheese and cracked pepper.",
    ],
    tips: "Season the sauce, not just the pasta water. A pinch of sugar rounds out sharp canned tomatoes.",
  },
  {
    id: "r-yogurt-parfait",
    title: "Greek Yogurt Parfait",
    subtitle: "Layered yogurt, banana, and crunchy oats in minutes.",
    prepMinutes: 5,
    cookMinutes: 0,
    servings: 1,
    difficulty: "Easy",
    mealType: "Quick Snack",
    tags: ["Vegetarian", "High Protein", "Quick & Easy"],
    ingredients: [
      { name: "Greek Yogurt", quantity: "1 cup", category: "Dairy", isPantryStaple: false },
      { name: "Bananas", quantity: "1 sliced", category: "Produce", isPantryStaple: false },
      { name: "Rolled Oats", quantity: "3 tbsp", category: "Pantry & Grains", isPantryStaple: true },
      { name: "Honey", quantity: "1 tsp", category: "Condiments", isPantryStaple: true },
    ],
    instructions: [
      "Spoon half the yogurt into a glass or jar.",
      "Add a layer of sliced banana and a sprinkle of oats.",
      "Repeat with the remaining yogurt, banana, and oats.",
      "Drizzle with honey and serve straight away.",
    ],
    tips: "Toast the oats in a dry pan for a couple of minutes for a nuttier, granola-like crunch.",
  },
  {
    id: "r-french-toast",
    title: "Sourdough French Toast",
    subtitle: "Custardy slices that revive day-old sourdough.",
    prepMinutes: 8,
    cookMinutes: 10,
    servings: 2,
    difficulty: "Easy",
    mealType: "Breakfast",
    tags: ["Vegetarian", "Budget Friendly", "Zero Waste Hero"],
    ingredients: [
      { name: "Sourdough Bread", quantity: "4 slices", category: "Bakery", isPantryStaple: false },
      { name: "Eggs", quantity: "2 large", category: "Dairy", isPantryStaple: false },
      { name: "Whole Milk", quantity: "100ml", category: "Dairy", isPantryStaple: false },
      { name: "Cinnamon", quantity: "1/2 tsp", category: "Condiments", isPantryStaple: true },
      { name: "Bananas", quantity: "1 sliced", category: "Produce", isPantryStaple: false },
    ],
    instructions: [
      "Whisk the eggs, milk, and cinnamon in a shallow dish.",
      "Soak each slice of sourdough for 20 seconds per side.",
      "Fry in a buttered pan over medium heat until golden, about 2–3 minutes per side.",
      "Top with sliced banana and a drizzle of honey or syrup.",
    ],
    tips: "Slightly stale bread soaks up the custard without falling apart — the whole point of this rescue.",
  },
  {
    id: "r-cheesy-garlic-bread",
    title: "Cheesy Garlic Sourdough",
    subtitle: "Crisp, molten garlic bread from leftover loaf.",
    prepMinutes: 6,
    cookMinutes: 12,
    servings: 2,
    difficulty: "Easy",
    mealType: "Quick Snack",
    tags: ["Vegetarian", "Budget Friendly", "Zero Waste Hero"],
    ingredients: [
      { name: "Sourdough Bread", quantity: "4 slices", category: "Bakery", isPantryStaple: false },
      { name: "Garlic", quantity: "2 cloves", category: "Produce", isPantryStaple: true },
      { name: "Cheddar Cheese", quantity: "80g grated", category: "Dairy", isPantryStaple: false },
      { name: "Olive Oil", quantity: "2 tbsp", category: "Condiments", isPantryStaple: true },
    ],
    instructions: [
      "Heat the oven to 200°C (400°F).",
      "Mix the crushed garlic into the olive oil and brush over the sourdough.",
      "Scatter the grated cheese generously over each slice.",
      "Bake for 10–12 minutes until bubbling and crisp at the edges.",
    ],
    tips: "Finish under the grill for 60 seconds if you want extra browning on top.",
  },
  {
    id: "r-chicken-fried-rice",
    title: "Pantry Chicken Skillet Rice",
    subtitle: "A savory one-pan supper built around staples.",
    prepMinutes: 10,
    cookMinutes: 18,
    servings: 3,
    difficulty: "Medium",
    mealType: "Lunch",
    tags: ["High Protein", "Budget Friendly"],
    ingredients: [
      { name: "Chicken Breast", quantity: "1 fillet, diced", category: "Meat & Poultry", isPantryStaple: false },
      { name: "Rice", quantity: "2 cups cooked", category: "Pantry & Grains", isPantryStaple: true },
      { name: "Eggs", quantity: "2 large", category: "Dairy", isPantryStaple: false },
      { name: "Garlic", quantity: "2 cloves", category: "Produce", isPantryStaple: true },
      { name: "Baby Spinach", quantity: "1 handful", category: "Produce", isPantryStaple: false },
      { name: "Soy Sauce", quantity: "2 tbsp", category: "Condiments", isPantryStaple: true },
    ],
    instructions: [
      "Brown the diced chicken in a hot, oiled skillet, then set aside.",
      "Scramble the eggs in the same pan and push to one side.",
      "Add the garlic and cooked rice, frying until the grains crisp slightly.",
      "Return the chicken, add the spinach and soy sauce, and toss until glossy and hot through.",
    ],
    tips: "Cold, day-old rice fries best. Fresh rice tends to clump and steam instead of crisping.",
  },
  {
    id: "r-tomato-soup",
    title: "Roasted Garlic Tomato Soup",
    subtitle: "A cozy, velvety bowl from the pantry shelf.",
    prepMinutes: 5,
    cookMinutes: 25,
    servings: 3,
    difficulty: "Easy",
    mealType: "Lunch",
    tags: ["Vegetarian", "Gluten Free", "Budget Friendly"],
    ingredients: [
      { name: "Canned Tomatoes", quantity: "2 cans", category: "Pantry & Grains", isPantryStaple: true },
      { name: "Garlic", quantity: "4 cloves", category: "Produce", isPantryStaple: true },
      { name: "Whole Milk", quantity: "100ml", category: "Dairy", isPantryStaple: false },
      { name: "Olive Oil", quantity: "2 tbsp", category: "Condiments", isPantryStaple: true },
    ],
    instructions: [
      "Sizzle the sliced garlic in olive oil until soft and fragrant.",
      "Add the canned tomatoes and a cup of water, then simmer for 15 minutes.",
      "Blend until smooth with an immersion blender.",
      "Stir in the milk, warm through gently, and season to taste.",
    ],
    tips: "Serve with the cheesy garlic sourdough for the ultimate zero-waste comfort lunch.",
  },
  {
    id: "r-banana-oat-cookies",
    title: "Two-Ingredient Banana Oat Cookies",
    subtitle: "Naturally sweet cookies that clear the fruit bowl.",
    prepMinutes: 10,
    cookMinutes: 15,
    servings: 4,
    difficulty: "Easy",
    mealType: "Baking",
    tags: ["Vegetarian", "Budget Friendly", "Zero Waste Hero"],
    ingredients: [
      { name: "Bananas", quantity: "2 ripe", category: "Produce", isPantryStaple: false },
      { name: "Rolled Oats", quantity: "1 cup", category: "Pantry & Grains", isPantryStaple: true },
      { name: "Cinnamon", quantity: "1/2 tsp", category: "Condiments", isPantryStaple: true },
    ],
    instructions: [
      "Heat the oven to 180°C (350°F) and line a tray.",
      "Mash the bananas until smooth and stir in the oats and cinnamon.",
      "Spoon small mounds onto the tray and flatten slightly.",
      "Bake for 13–15 minutes until set at the edges.",
    ],
    tips: "Fold in any odds and ends — a handful of chocolate chips, seeds, or chopped nuts all work beautifully.",
  },
]
